version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: "fs-extra"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      minor_versions:
        update-types:
          - 'minor'
          - 'patch'
  - package-ecosystem: "bundler"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      minor_versions:
        update-types:
          - 'minor'
          - 'patch'
