name: 'Setup CLI deps'
description: 'Sets up dependencies necessary for cli'
inputs:
  node-version:
    required: true
    description: 'Node version'
runs:
  using: 'composite'
  steps:
    - name: Set Git configuration
      run: |
        git config --global user.email "cli-foundations@shopify.com"
        git config --global user.name "CLI Foundations"
      shell: bash
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install pnpm
      uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # pin@v2.2.4
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false
    - name: Get pnpm store directory
      id: pnpm-cache-path
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache-path.outputs.STORE_PATH }}
        key: ${{ runner.os }}-${{ inputs.node-version }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.node-version }}-pnpm-store-
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
